# -*- coding: utf-8 -*-
"""NEW_langmuir_plots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c4eBx7C2CVv1myboIHCcdURMBwoDzRRS
"""

# @title Notebook Setup { display-mode: "form" }
# Import the main modules used in this worksheet
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
# Load the google drive with your files
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import matplotlib.pyplot as plt

# The following needs to be the path of the folder with all your datafile in .ntb format
# Open the file icon on the left, find the folder where the data is contained, click the three dots on folder and click copy path, add a backslash at the end
path = '/content/drive/MyDrive/Langmuir_plots/'

# Define a list of dictionaries with file information
# Copy and paste a new file dictionary, change the 'name' to the exact file name, change the label to reflect what should be plotted on the graph
files = [
    {'path': path, 'name': 'cdc_DPPC_PS_Bottom.ntb', 'label': 'DPPC_PS', 'skiprows': 38},
    {'path': path, 'name': 'cdc_test3_DPPC.ntb', 'label': 'DPPC3', 'skiprows': 38},
    {'path': path, 'name': 'cdc_test2_DPPC.ntb', 'label': 'DPPC2', 'skiprows': 38},

    # Add more files here if needed
]

plt.figure(figsize=(10, 6))  # Create a figure

# Iterate over the files list to read data and plot
for file in files:
    # Construct the full path to the file
    path = file['path'] + file['name']

    # Read the file into a DataFrame
    df = pd.read_csv(path, skiprows=file['skiprows'], sep=';')

    # Extract relevant columns
    total_area = df['Area']
    pressure = df['Pressure']

    # Plot the data
    plt.plot(total_area, pressure, linestyle='-', linewidth=2, label=file['label'])

# Set plot titles and labels
plt.title('Area vs Pressure')
plt.xlabel('Area')
plt.ylabel('Pressure')
plt.legend()
plt.grid(True)

# Show the plot
plt.show()